// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface ErrorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.ErrorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.log.v2.LogRequest log_request = 1;</code>
   */
  boolean hasLogRequest();
  /**
   * <code>.log.v2.LogRequest log_request = 1;</code>
   */
  sirup.service.log.rpc.proto.LogRequest getLogRequest();
  /**
   * <code>.log.v2.LogRequest log_request = 1;</code>
   */
  sirup.service.log.rpc.proto.LogRequestOrBuilder getLogRequestOrBuilder();
}
