// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

/**
 * Protobuf type {@code log.v2.ErrorResponse}
 */
public  final class ErrorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:log.v2.ErrorResponse)
    ErrorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ErrorResponse.newBuilder() to construct.
  private ErrorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ErrorResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ErrorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            sirup.service.log.rpc.proto.LogResponse.Builder subBuilder = null;
            if (logResponse_ != null) {
              subBuilder = logResponse_.toBuilder();
            }
            logResponse_ = input.readMessage(sirup.service.log.rpc.proto.LogResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(logResponse_);
              logResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sirup.service.log.rpc.proto.Log.internal_static_log_v2_ErrorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sirup.service.log.rpc.proto.Log.internal_static_log_v2_ErrorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sirup.service.log.rpc.proto.ErrorResponse.class, sirup.service.log.rpc.proto.ErrorResponse.Builder.class);
  }

  public static final int LOG_RESPONSE_FIELD_NUMBER = 1;
  private sirup.service.log.rpc.proto.LogResponse logResponse_;
  /**
   * <code>.log.v2.LogResponse log_response = 1;</code>
   */
  public boolean hasLogResponse() {
    return logResponse_ != null;
  }
  /**
   * <code>.log.v2.LogResponse log_response = 1;</code>
   */
  public sirup.service.log.rpc.proto.LogResponse getLogResponse() {
    return logResponse_ == null ? sirup.service.log.rpc.proto.LogResponse.getDefaultInstance() : logResponse_;
  }
  /**
   * <code>.log.v2.LogResponse log_response = 1;</code>
   */
  public sirup.service.log.rpc.proto.LogResponseOrBuilder getLogResponseOrBuilder() {
    return getLogResponse();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (logResponse_ != null) {
      output.writeMessage(1, getLogResponse());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (logResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLogResponse());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sirup.service.log.rpc.proto.ErrorResponse)) {
      return super.equals(obj);
    }
    sirup.service.log.rpc.proto.ErrorResponse other = (sirup.service.log.rpc.proto.ErrorResponse) obj;

    boolean result = true;
    result = result && (hasLogResponse() == other.hasLogResponse());
    if (hasLogResponse()) {
      result = result && getLogResponse()
          .equals(other.getLogResponse());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLogResponse()) {
      hash = (37 * hash) + LOG_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getLogResponse().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.log.rpc.proto.ErrorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sirup.service.log.rpc.proto.ErrorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code log.v2.ErrorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:log.v2.ErrorResponse)
      sirup.service.log.rpc.proto.ErrorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sirup.service.log.rpc.proto.Log.internal_static_log_v2_ErrorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sirup.service.log.rpc.proto.Log.internal_static_log_v2_ErrorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sirup.service.log.rpc.proto.ErrorResponse.class, sirup.service.log.rpc.proto.ErrorResponse.Builder.class);
    }

    // Construct using sirup.service.log.rpc.proto.ErrorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (logResponseBuilder_ == null) {
        logResponse_ = null;
      } else {
        logResponse_ = null;
        logResponseBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sirup.service.log.rpc.proto.Log.internal_static_log_v2_ErrorResponse_descriptor;
    }

    @java.lang.Override
    public sirup.service.log.rpc.proto.ErrorResponse getDefaultInstanceForType() {
      return sirup.service.log.rpc.proto.ErrorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sirup.service.log.rpc.proto.ErrorResponse build() {
      sirup.service.log.rpc.proto.ErrorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sirup.service.log.rpc.proto.ErrorResponse buildPartial() {
      sirup.service.log.rpc.proto.ErrorResponse result = new sirup.service.log.rpc.proto.ErrorResponse(this);
      if (logResponseBuilder_ == null) {
        result.logResponse_ = logResponse_;
      } else {
        result.logResponse_ = logResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sirup.service.log.rpc.proto.ErrorResponse) {
        return mergeFrom((sirup.service.log.rpc.proto.ErrorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sirup.service.log.rpc.proto.ErrorResponse other) {
      if (other == sirup.service.log.rpc.proto.ErrorResponse.getDefaultInstance()) return this;
      if (other.hasLogResponse()) {
        mergeLogResponse(other.getLogResponse());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sirup.service.log.rpc.proto.ErrorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sirup.service.log.rpc.proto.ErrorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private sirup.service.log.rpc.proto.LogResponse logResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sirup.service.log.rpc.proto.LogResponse, sirup.service.log.rpc.proto.LogResponse.Builder, sirup.service.log.rpc.proto.LogResponseOrBuilder> logResponseBuilder_;
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    public boolean hasLogResponse() {
      return logResponseBuilder_ != null || logResponse_ != null;
    }
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    public sirup.service.log.rpc.proto.LogResponse getLogResponse() {
      if (logResponseBuilder_ == null) {
        return logResponse_ == null ? sirup.service.log.rpc.proto.LogResponse.getDefaultInstance() : logResponse_;
      } else {
        return logResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    public Builder setLogResponse(sirup.service.log.rpc.proto.LogResponse value) {
      if (logResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        logResponse_ = value;
        onChanged();
      } else {
        logResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    public Builder setLogResponse(
        sirup.service.log.rpc.proto.LogResponse.Builder builderForValue) {
      if (logResponseBuilder_ == null) {
        logResponse_ = builderForValue.build();
        onChanged();
      } else {
        logResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    public Builder mergeLogResponse(sirup.service.log.rpc.proto.LogResponse value) {
      if (logResponseBuilder_ == null) {
        if (logResponse_ != null) {
          logResponse_ =
            sirup.service.log.rpc.proto.LogResponse.newBuilder(logResponse_).mergeFrom(value).buildPartial();
        } else {
          logResponse_ = value;
        }
        onChanged();
      } else {
        logResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    public Builder clearLogResponse() {
      if (logResponseBuilder_ == null) {
        logResponse_ = null;
        onChanged();
      } else {
        logResponse_ = null;
        logResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    public sirup.service.log.rpc.proto.LogResponse.Builder getLogResponseBuilder() {
      
      onChanged();
      return getLogResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    public sirup.service.log.rpc.proto.LogResponseOrBuilder getLogResponseOrBuilder() {
      if (logResponseBuilder_ != null) {
        return logResponseBuilder_.getMessageOrBuilder();
      } else {
        return logResponse_ == null ?
            sirup.service.log.rpc.proto.LogResponse.getDefaultInstance() : logResponse_;
      }
    }
    /**
     * <code>.log.v2.LogResponse log_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sirup.service.log.rpc.proto.LogResponse, sirup.service.log.rpc.proto.LogResponse.Builder, sirup.service.log.rpc.proto.LogResponseOrBuilder> 
        getLogResponseFieldBuilder() {
      if (logResponseBuilder_ == null) {
        logResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sirup.service.log.rpc.proto.LogResponse, sirup.service.log.rpc.proto.LogResponse.Builder, sirup.service.log.rpc.proto.LogResponseOrBuilder>(
                getLogResponse(),
                getParentForChildren(),
                isClean());
        logResponse_ = null;
      }
      return logResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:log.v2.ErrorResponse)
  }

  // @@protoc_insertion_point(class_scope:log.v2.ErrorResponse)
  private static final sirup.service.log.rpc.proto.ErrorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sirup.service.log.rpc.proto.ErrorResponse();
  }

  public static sirup.service.log.rpc.proto.ErrorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ErrorResponse>
      PARSER = new com.google.protobuf.AbstractParser<ErrorResponse>() {
    @java.lang.Override
    public ErrorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ErrorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ErrorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ErrorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sirup.service.log.rpc.proto.ErrorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

