// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface HealthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.HealthRequest)
    com.google.protobuf.MessageOrBuilder {
}
