// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface HealthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.HealthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 health_code = 1;</code>
   */
  int getHealthCode();
}
