// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

/**
 * Protobuf type {@code log.v2.InfoRequest}
 */
public  final class InfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:log.v2.InfoRequest)
    InfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InfoRequest.newBuilder() to construct.
  private InfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InfoRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InfoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            sirup.service.log.rpc.proto.LogRequest.Builder subBuilder = null;
            if (logRequest_ != null) {
              subBuilder = logRequest_.toBuilder();
            }
            logRequest_ = input.readMessage(sirup.service.log.rpc.proto.LogRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(logRequest_);
              logRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sirup.service.log.rpc.proto.Log.internal_static_log_v2_InfoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sirup.service.log.rpc.proto.Log.internal_static_log_v2_InfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sirup.service.log.rpc.proto.InfoRequest.class, sirup.service.log.rpc.proto.InfoRequest.Builder.class);
  }

  public static final int LOG_REQUEST_FIELD_NUMBER = 1;
  private sirup.service.log.rpc.proto.LogRequest logRequest_;
  /**
   * <code>.log.v2.LogRequest log_request = 1;</code>
   */
  public boolean hasLogRequest() {
    return logRequest_ != null;
  }
  /**
   * <code>.log.v2.LogRequest log_request = 1;</code>
   */
  public sirup.service.log.rpc.proto.LogRequest getLogRequest() {
    return logRequest_ == null ? sirup.service.log.rpc.proto.LogRequest.getDefaultInstance() : logRequest_;
  }
  /**
   * <code>.log.v2.LogRequest log_request = 1;</code>
   */
  public sirup.service.log.rpc.proto.LogRequestOrBuilder getLogRequestOrBuilder() {
    return getLogRequest();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (logRequest_ != null) {
      output.writeMessage(1, getLogRequest());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (logRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLogRequest());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sirup.service.log.rpc.proto.InfoRequest)) {
      return super.equals(obj);
    }
    sirup.service.log.rpc.proto.InfoRequest other = (sirup.service.log.rpc.proto.InfoRequest) obj;

    boolean result = true;
    result = result && (hasLogRequest() == other.hasLogRequest());
    if (hasLogRequest()) {
      result = result && getLogRequest()
          .equals(other.getLogRequest());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLogRequest()) {
      hash = (37 * hash) + LOG_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getLogRequest().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.log.rpc.proto.InfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sirup.service.log.rpc.proto.InfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code log.v2.InfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:log.v2.InfoRequest)
      sirup.service.log.rpc.proto.InfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sirup.service.log.rpc.proto.Log.internal_static_log_v2_InfoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sirup.service.log.rpc.proto.Log.internal_static_log_v2_InfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sirup.service.log.rpc.proto.InfoRequest.class, sirup.service.log.rpc.proto.InfoRequest.Builder.class);
    }

    // Construct using sirup.service.log.rpc.proto.InfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (logRequestBuilder_ == null) {
        logRequest_ = null;
      } else {
        logRequest_ = null;
        logRequestBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sirup.service.log.rpc.proto.Log.internal_static_log_v2_InfoRequest_descriptor;
    }

    @java.lang.Override
    public sirup.service.log.rpc.proto.InfoRequest getDefaultInstanceForType() {
      return sirup.service.log.rpc.proto.InfoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public sirup.service.log.rpc.proto.InfoRequest build() {
      sirup.service.log.rpc.proto.InfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sirup.service.log.rpc.proto.InfoRequest buildPartial() {
      sirup.service.log.rpc.proto.InfoRequest result = new sirup.service.log.rpc.proto.InfoRequest(this);
      if (logRequestBuilder_ == null) {
        result.logRequest_ = logRequest_;
      } else {
        result.logRequest_ = logRequestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sirup.service.log.rpc.proto.InfoRequest) {
        return mergeFrom((sirup.service.log.rpc.proto.InfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sirup.service.log.rpc.proto.InfoRequest other) {
      if (other == sirup.service.log.rpc.proto.InfoRequest.getDefaultInstance()) return this;
      if (other.hasLogRequest()) {
        mergeLogRequest(other.getLogRequest());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sirup.service.log.rpc.proto.InfoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sirup.service.log.rpc.proto.InfoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private sirup.service.log.rpc.proto.LogRequest logRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sirup.service.log.rpc.proto.LogRequest, sirup.service.log.rpc.proto.LogRequest.Builder, sirup.service.log.rpc.proto.LogRequestOrBuilder> logRequestBuilder_;
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    public boolean hasLogRequest() {
      return logRequestBuilder_ != null || logRequest_ != null;
    }
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    public sirup.service.log.rpc.proto.LogRequest getLogRequest() {
      if (logRequestBuilder_ == null) {
        return logRequest_ == null ? sirup.service.log.rpc.proto.LogRequest.getDefaultInstance() : logRequest_;
      } else {
        return logRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    public Builder setLogRequest(sirup.service.log.rpc.proto.LogRequest value) {
      if (logRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        logRequest_ = value;
        onChanged();
      } else {
        logRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    public Builder setLogRequest(
        sirup.service.log.rpc.proto.LogRequest.Builder builderForValue) {
      if (logRequestBuilder_ == null) {
        logRequest_ = builderForValue.build();
        onChanged();
      } else {
        logRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    public Builder mergeLogRequest(sirup.service.log.rpc.proto.LogRequest value) {
      if (logRequestBuilder_ == null) {
        if (logRequest_ != null) {
          logRequest_ =
            sirup.service.log.rpc.proto.LogRequest.newBuilder(logRequest_).mergeFrom(value).buildPartial();
        } else {
          logRequest_ = value;
        }
        onChanged();
      } else {
        logRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    public Builder clearLogRequest() {
      if (logRequestBuilder_ == null) {
        logRequest_ = null;
        onChanged();
      } else {
        logRequest_ = null;
        logRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    public sirup.service.log.rpc.proto.LogRequest.Builder getLogRequestBuilder() {
      
      onChanged();
      return getLogRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    public sirup.service.log.rpc.proto.LogRequestOrBuilder getLogRequestOrBuilder() {
      if (logRequestBuilder_ != null) {
        return logRequestBuilder_.getMessageOrBuilder();
      } else {
        return logRequest_ == null ?
            sirup.service.log.rpc.proto.LogRequest.getDefaultInstance() : logRequest_;
      }
    }
    /**
     * <code>.log.v2.LogRequest log_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sirup.service.log.rpc.proto.LogRequest, sirup.service.log.rpc.proto.LogRequest.Builder, sirup.service.log.rpc.proto.LogRequestOrBuilder> 
        getLogRequestFieldBuilder() {
      if (logRequestBuilder_ == null) {
        logRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sirup.service.log.rpc.proto.LogRequest, sirup.service.log.rpc.proto.LogRequest.Builder, sirup.service.log.rpc.proto.LogRequestOrBuilder>(
                getLogRequest(),
                getParentForChildren(),
                isClean());
        logRequest_ = null;
      }
      return logRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:log.v2.InfoRequest)
  }

  // @@protoc_insertion_point(class_scope:log.v2.InfoRequest)
  private static final sirup.service.log.rpc.proto.InfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sirup.service.log.rpc.proto.InfoRequest();
  }

  public static sirup.service.log.rpc.proto.InfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<InfoRequest>() {
    @java.lang.Override
    public InfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InfoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sirup.service.log.rpc.proto.InfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

