// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public final class Log {
  private Log() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_HealthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_HealthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_HealthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_HealthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_DebugRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_DebugRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_DebugResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_DebugResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_InfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_InfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_InfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_InfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_WarnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_WarnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_WarnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_WarnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_ErrorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_ErrorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_LogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_LogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_log_v2_LogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_log_v2_LogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017sirup_log.proto\022\006log.v2\"\017\n\rHealthReque" +
      "st\"%\n\016HealthResponse\022\023\n\013health_code\030\001 \001(" +
      "\005\"7\n\014DebugRequest\022\'\n\013log_request\030\001 \001(\0132\022" +
      ".log.v2.LogRequest\":\n\rDebugResponse\022)\n\014l" +
      "og_response\030\001 \001(\0132\023.log.v2.LogResponse\"6" +
      "\n\013InfoRequest\022\'\n\013log_request\030\001 \001(\0132\022.log" +
      ".v2.LogRequest\"9\n\014InfoResponse\022)\n\014log_re" +
      "sponse\030\001 \001(\0132\023.log.v2.LogResponse\"6\n\013War" +
      "nRequest\022\'\n\013log_request\030\001 \001(\0132\022.log.v2.L" +
      "ogRequest\"9\n\014WarnResponse\022)\n\014log_respons" +
      "e\030\001 \001(\0132\023.log.v2.LogResponse\"7\n\014ErrorReq" +
      "uest\022\'\n\013log_request\030\001 \001(\0132\022.log.v2.LogRe" +
      "quest\":\n\rErrorResponse\022)\n\014log_response\030\001" +
      " \001(\0132\023.log.v2.LogResponse\"5\n\nLogRequest\022" +
      "\017\n\007message\030\001 \001(\t\022\026\n\016sender_service\030\002 \001(\t" +
      "\"\033\n\013LogResponse\022\014\n\004code\030\001 \001(\0052\246\002\n\017SirupL" +
      "ogService\0229\n\006Health\022\025.log.v2.HealthReque" +
      "st\032\026.log.v2.HealthResponse\"\000\0226\n\005Debug\022\024." +
      "log.v2.DebugRequest\032\025.log.v2.DebugRespon" +
      "se\"\000\0223\n\004Info\022\023.log.v2.InfoRequest\032\024.log." +
      "v2.InfoResponse\"\000\0223\n\004Warn\022\023.log.v2.WarnR" +
      "equest\032\024.log.v2.WarnResponse\"\000\0226\n\005Error\022" +
      "\024.log.v2.ErrorRequest\032\025.log.v2.ErrorResp" +
      "onse\"\000B*\n\033sirup.service.log.rpc.protoB\003L" +
      "ogP\001\242\002\003SASb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_log_v2_HealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_log_v2_HealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_HealthRequest_descriptor,
        new java.lang.String[] { });
    internal_static_log_v2_HealthResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_log_v2_HealthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_HealthResponse_descriptor,
        new java.lang.String[] { "HealthCode", });
    internal_static_log_v2_DebugRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_log_v2_DebugRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_DebugRequest_descriptor,
        new java.lang.String[] { "LogRequest", });
    internal_static_log_v2_DebugResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_log_v2_DebugResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_DebugResponse_descriptor,
        new java.lang.String[] { "LogResponse", });
    internal_static_log_v2_InfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_log_v2_InfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_InfoRequest_descriptor,
        new java.lang.String[] { "LogRequest", });
    internal_static_log_v2_InfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_log_v2_InfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_InfoResponse_descriptor,
        new java.lang.String[] { "LogResponse", });
    internal_static_log_v2_WarnRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_log_v2_WarnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_WarnRequest_descriptor,
        new java.lang.String[] { "LogRequest", });
    internal_static_log_v2_WarnResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_log_v2_WarnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_WarnResponse_descriptor,
        new java.lang.String[] { "LogResponse", });
    internal_static_log_v2_ErrorRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_log_v2_ErrorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_ErrorRequest_descriptor,
        new java.lang.String[] { "LogRequest", });
    internal_static_log_v2_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_log_v2_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_ErrorResponse_descriptor,
        new java.lang.String[] { "LogResponse", });
    internal_static_log_v2_LogRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_log_v2_LogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_LogRequest_descriptor,
        new java.lang.String[] { "Message", "SenderService", });
    internal_static_log_v2_LogResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_log_v2_LogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_log_v2_LogResponse_descriptor,
        new java.lang.String[] { "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
