// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface LogDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.LogDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string level = 1;</code>
   */
  java.lang.String getLevel();
  /**
   * <code>string level = 1;</code>
   */
  com.google.protobuf.ByteString
      getLevelBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string date = 3;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
