// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface LogFromResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.LogFromResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool found = 1;</code>
   */
  boolean getFound();

  /**
   * <code>repeated .log.v2.LogDTO logs = 2;</code>
   */
  java.util.List<sirup.service.log.rpc.proto.LogDTO> 
      getLogsList();
  /**
   * <code>repeated .log.v2.LogDTO logs = 2;</code>
   */
  sirup.service.log.rpc.proto.LogDTO getLogs(int index);
  /**
   * <code>repeated .log.v2.LogDTO logs = 2;</code>
   */
  int getLogsCount();
  /**
   * <code>repeated .log.v2.LogDTO logs = 2;</code>
   */
  java.util.List<? extends sirup.service.log.rpc.proto.LogDTOOrBuilder> 
      getLogsOrBuilderList();
  /**
   * <code>repeated .log.v2.LogDTO logs = 2;</code>
   */
  sirup.service.log.rpc.proto.LogDTOOrBuilder getLogsOrBuilder(
      int index);
}
