// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface LogFromRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.LogFromRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.log.v2.Credentials admin_credentials = 1;</code>
   */
  boolean hasAdminCredentials();
  /**
   * <code>.log.v2.Credentials admin_credentials = 1;</code>
   */
  sirup.service.log.rpc.proto.Credentials getAdminCredentials();
  /**
   * <code>.log.v2.Credentials admin_credentials = 1;</code>
   */
  sirup.service.log.rpc.proto.CredentialsOrBuilder getAdminCredentialsOrBuilder();

  /**
   * <code>string log_name = 2;</code>
   */
  java.lang.String getLogName();
  /**
   * <code>string log_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getLogNameBytes();
}
