// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface LogListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.LogListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string log_list = 1;</code>
   */
  java.util.List<java.lang.String>
      getLogListList();
  /**
   * <code>repeated string log_list = 1;</code>
   */
  int getLogListCount();
  /**
   * <code>repeated string log_list = 1;</code>
   */
  java.lang.String getLogList(int index);
  /**
   * <code>repeated string log_list = 1;</code>
   */
  com.google.protobuf.ByteString
      getLogListBytes(int index);
}
