// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface LogListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.LogListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.log.v2.Credentials admin_credentials = 1;</code>
   */
  boolean hasAdminCredentials();
  /**
   * <code>.log.v2.Credentials admin_credentials = 1;</code>
   */
  sirup.service.log.rpc.proto.Credentials getAdminCredentials();
  /**
   * <code>.log.v2.Credentials admin_credentials = 1;</code>
   */
  sirup.service.log.rpc.proto.CredentialsOrBuilder getAdminCredentialsOrBuilder();
}
