// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface LogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.proto.LogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string senderService = 2;</code>
   */
  java.lang.String getSenderService();
  /**
   * <code>string senderService = 2;</code>
   */
  com.google.protobuf.ByteString
      getSenderServiceBytes();
}
