// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_log.proto

package sirup.service.log.rpc.proto;

public interface WarnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:log.v2.WarnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.log.v2.LogResponse log_response = 1;</code>
   */
  boolean hasLogResponse();
  /**
   * <code>.log.v2.LogResponse log_response = 1;</code>
   */
  sirup.service.log.rpc.proto.LogResponse getLogResponse();
  /**
   * <code>.log.v2.LogResponse log_response = 1;</code>
   */
  sirup.service.log.rpc.proto.LogResponseOrBuilder getLogResponseOrBuilder();
}
